### ISSUE TITLE
is this in development mode?

### ISSUE THREAD

**Issue by ksyp-7** [natrixdev/snapchat-score-botter-website#1]

**Comment by HydroYT** [comment]
yes im making it now with my friend 
yes im making it now with my friend 
yes im making it now with my friend 
yes im making it now with my friend 
yes im making it now with my friend 
yes im making it now with my friend 
yes im making it now with my friend 
yes im making it now with my friend 
yes im making it now with my friend 
yes im making it now with my friend 
yes im making it now with my friend 
yes im making it now with my friend 
yes im making it now with my friend 
yes im making it now with my friend 
yes im making it now with my friend 
yes im making it now with my friend 
yes im making it now with my friend 
yes im making it now with my friend 
yes im making it now with my friend

**Comment by natrixdev** [comment]
no, but you need to add your own code, here i only give you the front code
